### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by mponts30** [bitmovin/analytics-google-datastudio-connector#1]
The connector was working for me before, but now I'm getting this error. Am I doing something wrong or is something broken in the connector? Thanks.
![image](https://user-images.githubusercontent.com/47334750/57194690-a6825100-6f17-11e9-9181-e31febfa6709.png)

**Comment by LudoMichaud** [comment]
hi @mponts30 
Thanks for opening this issue.
I couldn't reproduce this behaviour, as it seems. Are you still observing the same ? 
Please feel free out reach out to support@bitmovin.com if this is the case, so myself or my colleagues from the support team can take a look. 
Thanks

**Comment by peterpf** [comment]
We updated the link in the [README](https://github.com/bitmovin/analytics-google-datastudio-connector/blob/master/README.md) file. It now refers to the latest stable version of the connector.
