### ISSUE TITLE
VIDEO_TITLE is not included as dimension

### ISSUE THREAD

**Issue by mlg-tdeng** [bitmovin/analytics-google-datastudio-connector#4]
In the list of dimension, I don't see VIDEO_TITLE is included. This makes no video title can be queried even if it is added in source config. I see VIDEO_ID is among the list however its value is `null` as shown below. 
![image](https://user-images.githubusercontent.com/34727368/64202446-047f6080-ce46-11e9-88e5-06dbd431390a.png)
How to setup in BitMovin player so that VIDEO_ID value is not `null` in Google Data Studio report? and is it necessary to add VIDEO_TITLE as dimension?

**Comment by jonathanhperry** [comment]
`VIDEO_TITLE` is now available as a dimension
